import React from 'react'

export const metadata = {
	title: 'Next Pizza | Dashboard',
	description: 'Generated by Next.js'
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			DASHBOADR HEADER
			<body>{children}</body>
		</html>
	)
}
